### ISSUE TITLE
Sync color module over multiple ranks when using getMinMax

### ISSUE THREAD

**Issue by brtwrst** [vistle/vistle#18]
When color modules on different ranks calculate the lower and upper values themselves, they calculate different values on each rank and the colors do not fit together in the composited picture.
![color](https://cloud.githubusercontent.com/assets/6873862/3717354/e07c7f40-1623-11e4-89a9-fa30c223b308.png)

**Comment by aumuell** [comment]
fixed in 95a62ea29195bade344c783b56dd8379c7b6700d
