### ISSUE TITLE
DisCOVERay stuck after re-linking input

### ISSUE THREAD

**Issue by hpcdgrie** [vistle/vistle#44]
DisCOVERay on Hawk, COVER on visent.
On visent: go to /mnt/raid/soft/vistleHawk and start vistle
On Hawk compute node: source /opt/hlrs/non-spack/visualization/spack/share/spack/setup-env.sh
spack load vistle
vistle -b -c visent.hlrs.de:port
load /mnt/raid/soft/vistleHawk/RHR_mesh_not_working.vsl
execute
remove links between DomainSurface and DisCOVERay and between Color and DisCOVERay
recreate removed links
execute

**Comment by aumuell** [comment]
I think this is because of https://github.com/embree/embree/issues/354
